/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project.tampilan;


import project.aksi.AksiUser;
import project.input.InputUser;
import project.data.User;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Irvan
 */
public class TampilanUser extends javax.swing.JFrame {
    List<User> record = new ArrayList<User>();
    AksiUser usServis;
    int row;

    /**
     * Creates new form TampilanUser
     */
    public TampilanUser() {
        initComponents();
        usServis = new InputUser();
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            
            public void valueChanged(ListSelectionEvent e){
            row=jTable1.getSelectedRow();
            if(row!=-1){
               isiText();
            }
            }
        });
        this.statusAwal();
    }
    
    void loadData(){
        try{
            record = usServis.getAll();
        }catch(SQLException ex){
            Logger.getLogger(TampilanUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void isiTabel(){
        Object data[][] = new Object[record.size()][4];
        int x=0;
        for(User us:record){
            data[x][0]=us.getId_user();
            data[x][1]=us.getNama();
            data[x][2]=us.getEmail();
            data[x][3]=us.getJenis();
            x++;
        }
        String judul[]={"User Name","Nama","Email","Jenis Kelamin"};
        jTable1.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(jTable1);
    }
    
    void isiText(){
        User us = record.get(row);
        txtId_user.setText(us.getId_user());
        txtNama.setText(us.getNama());
        txtEmail.setText(us.getEmail());
        txtJenis.setText(us.getJenis());
    }
    
    void kosongkanText(){
        txtId_user.setText("");
        txtNama.setText("");
        txtEmail.setText("");
        txtJenis.setText("");
         txtId_user.requestFocus();
    }
    
    void statusAwal(){
        kosongkanText();
        loadData();
        isiTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbuser = new javax.swing.JLabel();
        lbnama = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        lbjenis = new javax.swing.JLabel();
        txtId_user = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtJenis = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        Batal = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tampilan User");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbuser.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lbuser.setText("User Name");

        lbnama.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lbnama.setText("Nama");

        lbemail.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lbemail.setText("Email");

        lbjenis.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lbjenis.setText("Jenis Kelamin");

        txtId_user.setBackground(new java.awt.Color(240, 229, 173));
        txtId_user.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtNama.setBackground(new java.awt.Color(240, 229, 173));
        txtNama.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtNama.setForeground(new java.awt.Color(0, 9, 9));

        txtEmail.setBackground(new java.awt.Color(240, 229, 173));
        txtEmail.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtJenis.setBackground(new java.awt.Color(240, 229, 173));
        txtJenis.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jTable1.setBackground(new java.awt.Color(240, 229, 173));
        jTable1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(7, 250, 248));
        jTable1.setSelectionBackground(new java.awt.Color(187, 252, 127));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        simpan.setBackground(new java.awt.Color(223, 252, 174));
        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/save.png"))); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        Batal.setBackground(new java.awt.Color(223, 252, 174));
        Batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/cancel.png"))); // NOI18N
        Batal.setText("Batal");
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(223, 252, 174));
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/update.png"))); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(223, 252, 174));
        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/delete.png"))); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Created by Sukma Wijaya - Irvan Abdurrahman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Batal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbuser)
                            .addComponent(lbemail)
                            .addComponent(lbnama)
                            .addComponent(lbjenis))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId_user, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(txtNama)
                            .addComponent(txtEmail)
                            .addComponent(txtJenis))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapus)))
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbuser)
                    .addComponent(txtId_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbemail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbjenis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(Batal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit)
                    .addComponent(hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("Utama");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
       try{ 
           // TODO add your handling code here:
            User u = new User();
            u.setId_user(txtId_user.getText());
            u.setNama(txtNama.getText());
            u.setEmail(txtEmail.getText());
            u.setJenis(txtJenis.getText());
            usServis.insert(u);
            this.statusAwal();
            JOptionPane.showMessageDialog(this, "Data Tersimpan");
       }catch(SQLException ex){
           Logger.getLogger(TampilanUser.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try{
            // TODO add your handling code here:
            User u = new User();
            u.setId_user(txtId_user.getText());
            u.setNama(txtNama.getText());
            u.setEmail(txtEmail.getText());
            u.setJenis(txtJenis.getText());
            usServis.update(u);
            this.statusAwal();
            JOptionPane.showMessageDialog(this, "Data telah diubah");
        }catch(SQLException ex){
            Logger.getLogger(TampilanUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try{
            // TODO add your handling code here:
            String Id_user = txtId_user.getText();
            usServis.delete(Id_user);
            this.statusAwal();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
        }catch (SQLException ex){
            Logger.getLogger(TampilanUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalActionPerformed
        // TODO add your handling code here:
       txtId_user.setText(null);
       txtNama.setText(null);
       txtEmail.setText(null);
       txtJenis.setText(null);
       txtId_user.requestFocus();
    }//GEN-LAST:event_BatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanUser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbjenis;
    private javax.swing.JLabel lbnama;
    private javax.swing.JLabel lbuser;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId_user;
    private javax.swing.JTextField txtJenis;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
